### logging
logging.level.com.taco.bbss: INFO

### Database
spring.jpa.show-sql: false


spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}