### logging
logging.level.org:
  postgresql.core.v3.ConnectionFactoryImpl: DEBUG
  hibernate.SQL: INFO

org.springframework: DEBUG

### Database
spring.datasource:
  url: jdbc:postgresql://${dbhost:localhost}:${dbport:5432}/${dbname:pm-brenda}
  username: ${dbuser:postgres}
  password: ${dbpass:root}

spring.jpa.show-sql: true

server.port: 8080
application.site: http://localhost:${server.port}/


